replicaCount: 1

fullnameOverride: "rereverb-user-service"

image: "rereverb-user-service:0.1.0"

service:
  type: NodePort
  port: 8080

externalPostgresql:
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlUrl: "jdbc:postgresql://pg-postgresql:5432/postgres"