apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: rereverb-order-service
    context: .
deploy:
  helm:
    releases:
    - name: rereverb-order-service
      chartPath: order-service-chart
      skipBuildDependencies: false
      values:
        image: rereverb-order-service
