apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rereverb-order-service-chart.fullname" . }}
  labels:
    {{- include "rereverb-order-service-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rereverb-order-service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rereverb-order-service-chart.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.externalPostgresql.postgresqlUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.externalPostgresql.postgresqlUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.externalPostgresql.postgresqlPassword }}
            - name: REREVERB_SERVICEURLS_ADVERTISEMENT
              value: {{ .Values.rereverb.serviceUrls.advertisement }}
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS
              value: {{ .Values.kafka.consumer.bootstrapservers }}
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAPSERVERS
              value: {{ .Values.kafka.producer.bootstrapservers }}