apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "rereverb-user-service-chart.fullname" . }}-secret"
type: Opaque
data:
  PG_USERNAME: {{ .Values.externalPostgresql.postgresqlUsername | b64enc | quote }}
  PG_PASSWORD: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
  PG_DATASOURCE: {{ .Values.externalPostgresql.postgresqlUrl | b64enc | quote }}
