server.port : 8085
spring:
  application.name: rereverb-advertisement-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari.auto-commit: false
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate:
      jdbc:
        time_zone: UTC
        batch_size: 20
      connection.provider_disables_autocommit: true
      default_schema: public
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    liquibase-schema: public
  servlet:
    contextPath: /api/
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  web.resources.add-mappings: false
  jackson:
    date-format: com.rereverb.advertisement.infrastructure.RFC3339DateFormat
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springfox.documentation.open-api.v3: path=/api-docs